language: c
compiler: clang
sudo: false
git:
  depth: 3
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libsdl2-dev
script:
  - mkdir build && cd build
  - CXX=clang++ CC=clang cmake .. && cmake --build .
