- pipeline: "build"
  trigger_mode: "ON_EVERY_PUSH"
  ref_name: "master"
  ref_type: "BRANCH"
  trigger_condition: "ALWAYS"
  actions:
  - action: "Clean up"
    type: "BUILD"
    working_directory: "/buddy/chip8emulator"
    docker_image_name: "library/ubuntu"
    docker_image_tag: "18.04"
    execute_commands:
    - "rm -rf build/"
    - "rm -rf *.tgz"
    mount_filesystem_path: "/buddy/chip8emulator"
    shell: "BASH"
    trigger_condition: "ALWAYS"
  - action: "Pack source code into a tarball"
    type: "BUILD"
    working_directory: "/buddy/chip8emulator"
    docker_image_name: "library/ubuntu"
    docker_image_tag: "18.04"
    execute_commands:
    - "BASENAME=$(basename `pwd`)"
    - "SRC_PKG=libchip8emu-src-master-${BUDDY_EXECUTION_REVISION_SHORT}.tgz"
    - "pushd .."
    - "tar czf ${SRC_PKG} \\"
    - "\t--exclude-vcs \\"
    - "\t--exclude='*.tgz' \\"
    - "\t--exclude build \\"
    - "\t--exclude CMakeLists.txt.user \\"
    - "\t${BASENAME}/"
    - "popd"
    - "mv ../${SRC_PKG} ."
    mount_filesystem_path: "/buddy/chip8emulator"
    shell: "BASH"
    trigger_condition: "ALWAYS"
  - action: "Execute: cmake --build ."
    type: "BUILD"
    working_directory: "/buddy/chip8emulator"
    docker_image_name: "rikorose/gcc-cmake"
    docker_image_tag: "latest"
    execute_commands:
    - "mkdir build"
    - "cd build/"
    - "cmake .."
    - "cmake --build ."
    setup_commands:
    - "apt-get update"
    - "apt-get -yq install libsdl2-dev"
    mount_filesystem_path: "/buddy/chip8emulator"
    shell: "BASH"
    trigger_condition: "ALWAYS"